language: python
python:
  - "3.5"

install:
  - pip install .
  - pip install codecov

script:
  - coverage run --source src test/main_test.py
  - coverage run --source src test/number_test.py
  - coverage report -m

after_success:
  - codecov
