language: python
python:
  - "3.5"

install:
  - pip install .
  - pip install codecov

script:
#  - coverage run test/main_test.py
  - coverage run test/number_test.py
  - coverage report -m

after_success:
  - codecov
